import { Action } from '../../beans/action';
import { HookType } from '../../beans/hookType';
import { SyncAction } from '../../beans/syncAction';
import { Listener } from '../../listener/listener';
import { RunData } from '../runData';
export declare class Collector {
    static instance: Collector;
    private readonly rawSuites;
    private readonly globalSuite;
    private readonly globalBeforeAll;
    private readonly globalAfterAll;
    private readonly globalBeforeEach;
    private readonly globalAfterEach;
    private readonly listeners;
    private readonly specPaths;
    private currentSpecFile;
    private currentSuite;
    static initialize(specsMasks: string[]): Collector;
    getData(): RunData;
    private constructor();
    private initTestsTree;
    addSuite(name: string, action: SyncAction): void;
    addTest(name: string): void;
    addHook(type: HookType, action: Action): void;
    addListener(listener: Listener): void;
    private parseSpecsMask;
    private isLocalSuite;
    private addSuiteTest;
    private addGlobalTest;
}
